eureka:
  client:
    register-with-eureka: false

server:
  port: 8081

spring:
  application:
    name: microservicio-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/** # Corrige la clave "path" con "Path" (mayúscula)

        - id: paciente
          uri: http://localhost:8091
          predicates:
            - Path=/api/paciente/**
